// Copyright (c) 2026 yus3nable
// SPDX-License-Identifier: MIT

#ifndef TESTS_TEST_NAMES_H_
#define TESTS_TEST_NAMES_H_

#include "mini_llama/backend.h"
#include "mini_llama/batch.h"
#include "mini_llama/chat.h"
#include "mini_llama/context.h"
#include "mini_llama/cuda_attention.h"
#include "mini_llama/cuda_kv_cache.h"
#include "mini_llama/cuda_matmul.h"
#include "mini_llama/cuda_ops.h"
#include "mini_llama/cuda_quant.h"
#include "mini_llama/cuda_runtime.h"
#include "mini_llama/cuda_tensor.h"
#include "mini_llama/debug.h"
#include "mini_llama/forward.h"
#include "mini_llama/gguf.h"
#include "mini_llama/gguf_loader.h"
#include "mini_llama/gguf_tokenizer.h"
#include "mini_llama/kv_cache.h"
#include "mini_llama/loader.h"
#include "mini_llama/matmul_dispatch.h"
#include "mini_llama/model.h"
#include "mini_llama/ops.h"
#include "mini_llama/prompt_builder.h"
#include "mini_llama/quant.h"
#include "mini_llama/quantized_tensor.h"
#include "mini_llama/request_context.h"
#include "mini_llama/sampler.h"
#include "mini_llama/tensor.h"
#include "mini_llama/terminal.h"
#include "mini_llama/thread_pool.h"
#include "mini_llama/tokenizer.h"

using mini_llama::ArgMax;
using mini_llama::AsciiTokenizer;
using mini_llama::BackendConfig;
using mini_llama::BackendExecutionNote;
using mini_llama::BackendKind;
using mini_llama::BenchmarkResult;
using mini_llama::BlockQ40;
using mini_llama::BlockQ41;
using mini_llama::BlockQ80;
using mini_llama::BpeTokenizer;
using mini_llama::ChatMessage;
using mini_llama::ChatSession;
using mini_llama::CreateBpeTokenizer;
using mini_llama::CreateGgufTokenizer;
using mini_llama::CreateTokenizer;
using mini_llama::CudaAttentionBuilt;
using mini_llama::CudaAttentionDecode;
using mini_llama::CudaAttentionDecodeDeviceInput;
using mini_llama::CudaDeviceBuffer;
using mini_llama::CudaDeviceCount;
using mini_llama::CudaDeviceInfo;
using mini_llama::CudaElementwiseAdd;
using mini_llama::CudaElementwiseAddDeviceInput;
using mini_llama::CudaElementwiseAddDeviceWeight;
using mini_llama::CudaElementwiseMul;
using mini_llama::CudaElementwiseMulDeviceInput;
using mini_llama::CudaEmbeddingLookupDeviceWeight;
using mini_llama::CudaFormatDeviceInfo;
using mini_llama::CudaGetDeviceInfo;
using mini_llama::CudaKvCache;
using mini_llama::CudaKvCacheBuilt;
using mini_llama::CudaLinear;
using mini_llama::CudaLinearDeviceInput;
using mini_llama::CudaMatmul;
using mini_llama::CudaMatmulBuilt;
using mini_llama::CudaOpsBuilt;
using mini_llama::CudaQ40Linear;
using mini_llama::CudaQ40LinearDeviceInput;
using mini_llama::CudaQ41Linear;
using mini_llama::CudaQ41LinearDeviceInput;
using mini_llama::CudaQ80Linear;
using mini_llama::CudaQ80LinearDeviceInput;
using mini_llama::CudaQuantBuilt;
using mini_llama::CudaRmsNorm;
using mini_llama::CudaRmsNormDeviceInput;
using mini_llama::CudaRmsNormDeviceWeight;
using mini_llama::CudaRuntimeBuilt;
using mini_llama::CudaSetDevice;
using mini_llama::CudaSilu;
using mini_llama::CudaSiluDeviceInput;
using mini_llama::CudaTensor;
using mini_llama::CudaTensorFromHost;
using mini_llama::DequantizeFromQ40;
using mini_llama::DequantizeFromQ41;
using mini_llama::DequantizeFromQ80;
using mini_llama::DumpKvCacheInfo;
using mini_llama::DumpLogitsTopK;
using mini_llama::DumpTensorShape;
using mini_llama::ForwardBatch;
using mini_llama::ForwardToken;
using mini_llama::FormatRequestTraceEvents;
using mini_llama::FormatRequestTraceSummary;
using mini_llama::GetThreadCount;
using mini_llama::GgmlType;
using mini_llama::GgmlTypeName;
using mini_llama::GgufMetadataKv;
using mini_llama::GgufReader;
using mini_llama::GgufTensorInfo;
using mini_llama::GgufValueType;
using mini_llama::GgufValueTypeName;
using mini_llama::ITokenizer;
using mini_llama::JsonVocabTokenizer;
using mini_llama::kGgmlTypeF16;
using mini_llama::kGgmlTypeF32;
using mini_llama::kGgmlTypeQ40;
using mini_llama::kGgmlTypeQ80;
using mini_llama::kGgufTypeArray;
using mini_llama::kGgufTypeString;
using mini_llama::kGgufTypeUint32;
using mini_llama::kQ40BlockSize;
using mini_llama::kQ41BlockSize;
using mini_llama::kQ80BlockSize;
using mini_llama::KvCache;
using mini_llama::LayerWeights;
using mini_llama::Linear;
using mini_llama::LinearDispatch;
using mini_llama::LinearQ40;
using mini_llama::LinearQ41;
using mini_llama::LinearQ80;
using mini_llama::LoadChatTemplateFromGguf;
using mini_llama::LoadGgufModel;
using mini_llama::LoadModel;
using mini_llama::MakeTensor1D;
using mini_llama::MakeTensor2D;
using mini_llama::MakeTensor3D;
using mini_llama::MakeTensor4D;
using mini_llama::Matmul;
using mini_llama::MatmulDispatch;
using mini_llama::MatmulMode;
using mini_llama::MatmulQ40;
using mini_llama::MatmulQ80;
using mini_llama::MiniBatch;
using mini_llama::MiniLlamaContext;
using mini_llama::MiniLlamaModel;
using mini_llama::MiniSampler;
using mini_llama::ModelConfig;
using mini_llama::ModelCudaActivationCalls;
using mini_llama::ModelCudaAttentionCalls;
using mini_llama::ModelCudaAttentionCpuFallbacks;
using mini_llama::ModelCudaDeviceToHostBytes;
using mini_llama::ModelCudaDeviceToHostCopies;
using mini_llama::ModelCudaHostToDeviceBytes;
using mini_llama::ModelCudaHostToDeviceCopies;
using mini_llama::ModelCudaKvCacheReadBytes;
using mini_llama::ModelCudaKvCacheWriteBytes;
using mini_llama::ModelCudaLinearCalls;
using mini_llama::ModelCudaMemoryBytes;
using mini_llama::ModelCudaUploadedWeightCount;
using mini_llama::ModelManifest;
using mini_llama::ParallelFor;
using mini_llama::ParseManifest;
using mini_llama::PromptBuilder;
using mini_llama::QuantizedTensor;
using mini_llama::QuantizeModelToQ40;
using mini_llama::QuantizeModelToQ80;
using mini_llama::QuantizeToQ40;
using mini_llama::QuantizeToQ80;
using mini_llama::QuantType;
using mini_llama::RequestContext;
using mini_llama::StartRequest;
using mini_llama::ResetModelCudaRuntimeStats;
using mini_llama::RmsNorm;
using mini_llama::Rope;
using mini_llama::RopeType;
using mini_llama::RunBenchmark;
using mini_llama::SampleGreedy;
using mini_llama::SamplingParams;
using mini_llama::SetThreadCount;
using mini_llama::Softmax;
using mini_llama::SwiGlu;
using mini_llama::Tensor;
using mini_llama::Terminal;
using mini_llama::ToTensor;
using mini_llama::TraceEvent;
using mini_llama::UploadModelWeightsToCuda;

#endif  // TESTS_TEST_NAMES_H_
